/**
 * Seed script for Sabor de Casa - Cardápio Digital
 * Generates and seeds exactly 150 items:
 * - 30 ENTRADAS
 * - 30 PRATO PRINCIPAL
 * - 30 SOBREMESAS
 * - 30 BEBIDAS
 * - 30 CARTA DE VINHOS
 */

import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import { produtos, CATEGORIAS_VALIDAS } from "./drizzle/schema.js";
import { count } from "drizzle-orm";

interface RawProduct {
  nome: string;
  descricao: string;
  preco: string;
  categoria: (typeof CATEGORIAS_VALIDAS)[number];
  imagem: string;
  destaque?: number;
}

export const SEED_PRODUTOS: RawProduct[] = [
  // ================= ENTRADAS (30 ITENS) =================
  {
    nome: "Bruschetta Tradicional ao Pomodoro",
    descricao: "Fatias de pão rústico tostadas com azeite extravirgem, tomates frescos em cubos, manjericão e toque de alho.",
    preco: "28.50",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Carpaccio Clássico com Alcaparras",
    descricao: "Lâminas finíssimas de filé mignon cru temperadas com molho de mostarda dijon, alcaparras e lascas de parmesão.",
    preco: "46.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Dadinhos de Tapioca com Geleia de Pimenta",
    descricao: "Crocantes por fora e macios por dentro, feitos com queijo coalho e tapioca granulada artesanal.",
    preco: "34.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Ceviche de Tilápia com Leite de Tigre",
    descricao: "Peixe fresco marinado em suco de limão, cebola roxa, coentro fresco, pimenta dedo-de-moça e milho tostado.",
    preco: "42.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Bolinhos de Bacalhau da Serra",
    descricao: "Receita portuguesa tradicional com bacalhau Gadus morhua desfiado, batatas selecionadas e cheiro verde.",
    preco: "38.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Burrata Cremosa com Pesto Genovês",
    descricao: "Burrata fresca acompanhada de tomates confit adocicados, molho pesto artesanal e torradinhas aromatizadas.",
    preco: "52.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Camarão Empanado ao Coco",
    descricao: "Camarões médios empanados em crosta de coco ralado crocante servidos com molho agridoce picante.",
    preco: "58.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Provolone à Milanesa com Orégano",
    descricao: "Cubos de provolone empanados e dourados até ficarem crocantes por fora e derretidos por dentro.",
    preco: "32.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Pastéis Mistos de Boteco (6 unidades)",
    descricao: "Dupla de carne seca com catupiry, queijo meia cura artesanal e palmito fresco temperado.",
    preco: "29.90",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Tartar de Salmão com Avocado",
    descricao: "Salmão fresco picado na ponta da faca com avocado temperado, gergelim torrado e redução de teriyaki.",
    preco: "48.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Casquinha de Siri Gratinada",
    descricao: "Carne de siri nobre refogada em azeite de dendê suave, leite de coco e gratinada com parmesão.",
    preco: "36.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Coxinhas de Frango Defumado com Catupiry",
    descricao: "Massa leve de batata recheada com peito de frango defumado e Catupiry legítimo (6 unidades).",
    preco: "27.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mix de Queijos e Embutidos Artesanais",
    descricao: "Seleção com queijo canastra, gorgonzola, salame tipo italiano, presunto parma e azeitonas pretas marinadas.",
    preco: "64.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Polenta Frita Crocante com Parmesão",
    descricao: "Bastões de polenta cremosa frita, polvilhados com queijo grana padano e alecrim fresco.",
    preco: "25.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Iscas de Peixe Branco ao Molho Tártaro",
    descricao: "Filé de pescada branca empanado em farinha panko crocante, servido com molho tártaro da casa.",
    preco: "39.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Croquetes de Costela Bovina Desfiada",
    descricao: "Costela desfiada cozida lentamente no vinho tinto e ervas finas, empanada e crocante (5 unidades).",
    preco: "35.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cogumelos Salteados no Alho e Vinho Branco",
    descricao: "Mix de cogumelos paris e shimeji refogados no azeite com alho-poró, salsinha e manteiga clarificada.",
    preco: "38.50",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Guacamole Fresco com Totopos de Milho",
    descricao: "Abacate hass amassado com cebola roxa, tomates frescos, suco de lima e coentro, com nachos crocantes.",
    preco: "31.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Lula à Dorê com Maionese de Limão Siciliano",
    descricao: "Anéis de lula frescos empanados e fritos, servidos com gomos de limão e maionese aromática artesanal.",
    preco: "49.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Canapés de Salmão Defumado",
    descricao: "Pão de centeio com sour cream de dill, lâminas de salmão defumado norueguês e raspas de limão.",
    preco: "44.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Sopa de Cebola Gratinada à Francesa",
    descricao: "Cebolas douradas em caldo aromático de carne e vinho branco, finalizada com torrada e queijo gruyère gratinado.",
    preco: "33.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Espetinhos de Queijo Coalho com Melaço",
    descricao: "Grelhados na brasa com crosta dourada e servidos com fio de melaço de cana de açúcar artesanal.",
    preco: "26.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Salada Caesar com Tiras de Frango Grelhado",
    descricao: "Alface americana crocante, croutons amanteigados, molho caesar cremoso com parmesão ralado na hora.",
    preco: "37.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Salada Caprese Tradicional",
    descricao: "Fatias generosas de tomate caqui maduro, mussarela de búfala fresca, folhas de manjericão e azeite.",
    preco: "35.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mini Quiches de Alho-Poró com Queijo Minas",
    descricao: "Massa sablée crocante com recheio aveludado de alho-poró salteado e queijo minas curado (4 unidades).",
    preco: "28.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Brie Empanado com Geleia de Frutas Vermelhas",
    descricao: "Pedaço generoso de queijo brie empanado na farinha panko, servido aquecido com calda de frutas do bosque.",
    preco: "47.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Torresmo de Rolo com Limão Cravo",
    descricao: "Panceta suína crocante e pururucada por fora, suculenta por dentro, servida com fatias de limão cravo.",
    preco: "36.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Antipasto de Berinjela com Pão Italiano",
    descricao: "Berinjela assada lentamente com pimentões coloridos, passas brancas, nozes e azeite extravirgem.",
    preco: "27.50",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Carpaccio de Polvo ao Vinagrete Mediterrâneo",
    descricao: "Lâminas tenras de polvo cozido temperadas com azeite de ervas, páprica defumada e flor de sal.",
    preco: "56.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Caldinho de Feijão Amigo Carioca",
    descricao: "Caldo encorpado de feijão preto com tempero caseiro, servido com bacon crocante, couve fininha e torresmo.",
    preco: "21.00",
    categoria: "ENTRADAS",
    imagem: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
  },

  // ================= PRATO PRINCIPAL (30 ITENS) =================
  {
    nome: "Picanha Grelhada na Brasa com Farofa de Ovos",
    descricao: "Corte nobre alto grelhado ao ponto do cliente, guarnecido de arroz branco, farofa de ovos e vinagrete.",
    preco: "89.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Filé Mignon ao Molho Madeira com Risoto de Parmesão",
    descricao: "Medalhão de filé mignon grelhado com molho clássico de vinho madeira e cogumelos, com risoto cremoso.",
    preco: "84.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Bacalhau à Gomes de Sá Tradicional",
    descricao: "Lascadas generosas de bacalhau confitadas em azeite com batatas cozidas, cebolas douradas, ovos e azeitonas.",
    preco: "96.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Salmão Grelhado ao Molho de Maracujá",
    descricao: "Posta de salmão fresco selada na manteiga, regada com redução cítrica de maracujá e purê de mandioquinha.",
    preco: "78.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Moqueca Baiana Mista de Peixe e Camarão",
    descricao: "Cozida lentamente em panela de barro com leite de coco, azeite de dendê, pimentões, pirão e arroz de coco.",
    preco: "105.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Risoto de Cogumelos Silvestres com Trufas",
    descricao: "Arroz arbóreo italiano cremoso preparado com mix de funghi secchi, shiitake, manteiga e azeite trufado.",
    preco: "68.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Costela Bovina Premium Assada por 12 Horas",
    descricao: "Carne macia desmanchando no garfo, acompanhada de mandioca cozida amanteigada e vinagrete de feijão fradinho.",
    preco: "79.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Nhoque Rústico de Batata ao Ragu de Ossobuco",
    descricao: "Massa artesanal super leve cozida al dente com molho encorpado de tomates italianos e ossobuco desfiado.",
    preco: "65.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Filé de Frango Grelhado com Legumes Salteados",
    descricao: "Peito de frango marinado em ervas frescas, acompanhado de brócolis, cenouras baby e arroz integral.",
    preco: "46.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Feijoada Completa da Casa (Individual)",
    descricao: "Carnes nobres selecionadas, servidas com arroz, couve refogada no alho, bisteca grelhada, torresmo e laranjas.",
    preco: "62.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Polvo Grelhado com Batatas ao Murro",
    descricao: "Tentáculos de polvo macios com crosta grelhada, servidos com azeite de páprica doce e batatas amassadas ao forno.",
    preco: "112.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Ravioli de Búfala ao Molho Sugo e Manjericão",
    descricao: "Massa recheada artesanalmente com queijo de búfala e raspas de limão siciliano ao molho pomodoro rústico.",
    preco: "59.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Parmegiana de Filé Mignon da Casa",
    descricao: "Filé mignon empanado crocante, coberto com molho caseiro de tomates frescos, muçarela derretida e batata frita.",
    preco: "76.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Bife Ancho Angus com Batatas Rústicas",
    descricao: "350g de bife de ancho suculento com chimichurri argentino e batatas salpicadas com sal grosso e alecrim.",
    preco: "92.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Bobó de Camarão Cremoso na Moranga",
    descricao: "Creme aveludado de mandioca temperada com azeite de dendê e camarões rosa médios, servido com arroz branco.",
    preco: "86.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Lasanha Bolonhesa Clássica Gratinada",
    descricao: "Camadas fartas de massa fresca de ovos, ragu de carne bovina, molho bechamel cremoso e muito queijo gratinado.",
    preco: "54.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Strogonoff de Filé Mignon com Palha Artesanal",
    descricao: "Tiras de filé flambadas no conhaque, cogumelos frescos, creme de leite especial e batata palha fininha crocante.",
    preco: "61.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Costelinha Suína ao Barbecue com Purê de Maçã",
    descricao: "Costelinha macia caramelizada em molho barbecue artesanal defumado, com purê suave de maçã verde.",
    preco: "63.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Baião de Dois Sertanejo Especial",
    descricao: "Arroz com feijão de corda, carne seca desfiada, queijo coalho grelhado, bacon, calabresa e manteiga de garrafa.",
    preco: "58.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Espaguete ao Frutos do Mar",
    descricao: "Espaguete grano duro com camarões, lula, mexilhões e mariscos puxados no vinho branco e tomates cereja.",
    preco: "85.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Pato Confitado com Redução de Laranja",
    descricao: "Coxa e sobrecoxa de pato lentamente confitadas em gordura aromática, servidas com mousseline de batata doce.",
    preco: "88.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Tornedor Rossini com Foie Gras e Trufas",
    descricao: "Filé alto grelhado sobre fatia de brioche tostado, escalope de foie gras selado e demi-glace trufado.",
    preco: "135.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Arroz de Pato à Moda Portuguesa",
    descricao: "Arroz aromatizado com caldo de cozimento do pato, chouriço artesanal, azeitonas pretas e tostado ao forno.",
    preco: "77.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Truta Grelhada com Amêndoas Douradas",
    descricao: "Filé de truta fresca da serra salteado em manteiga e limão, polvilhado com lâminas de amêndoas tostadas.",
    preco: "69.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Risoto de Camarão com Queijo Brie e Aspargos",
    descricao: "Camarões grelhados no azeite combinados com arroz cremoso envolvido por pedaços generosos de brie e pontas de aspargos.",
    preco: "82.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Galinhada Caipira com Pequi e Cheiro Verde",
    descricao: "Frango caipira cozido lentamente no arroz aromático com temperos típicos do cerrado e açafrão da terra.",
    preco: "52.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Carré de Cordeiro em Crosta de Ervas",
    descricao: "Costelinhas de cordeiro tenras com crosta de mostarda e ervas da horta, com cuscuz marroquino perfumado.",
    preco: "118.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Tagliatelle ao Molho Pesto com Nozes",
    descricao: "Massa longa fresca de ovos envolvida em pesto de manjericão genovês, queijo pecorino e nozes crocantes.",
    preco: "55.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Lombo de Bacalhau Confitado com Grão de Bico",
    descricao: "Lombo alto cozido a baixa temperatura em azeite extravirgem com alho inteiro e salteado de grão de bico e couve.",
    preco: "109.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Hambúrguer Artesanal Angus com Queijo Cheddar",
    descricao: "200g de blend angus grelhado, queijo cheddar maturado, bacon defumado e maionese trufada no pão brioche amanteigado.",
    preco: "49.00",
    categoria: "PRATO PRINCIPAL",
    imagem: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
  },

  // ================= SOBREMESAS (30 ITENS) =================
  {
    nome: "Pudim de Leite Condensado da Vovó",
    descricao: "Textura aveludada sem furinhos, feito com leite condensado integral e calda caramelizada brilhante.",
    preco: "18.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Petit Gâteau de Chocolate Belga com Sorvete",
    descricao: "Bolinho quente com casca fininha e recheio cremoso e fluido de chocolate 70%, servido com sorvete de baunilha.",
    preco: "28.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Tiramisù Clássico Italiano",
    descricao: "Camadas de biscoito champagne embebidas em café expresso com licor amaretto e creme aerado de mascarpone.",
    preco: "29.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Cheesecake de Frutas Vermelhas Silvestres",
    descricao: "Base amanteigada de biscoitos com creme de queijo suave e geleia rústica de morangos, amoras e mirtilos.",
    preco: "26.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Crème Brûlée com Favos de Baunilha Bourbon",
    descricao: "Creme sedoso aromatizado com baunilha bourbon verdadeira e crosta fininha de açúcar maçaricado na hora.",
    preco: "27.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Churros Espanhóis com Doce de Leite Viçosa",
    descricao: "Mini churros dourados e crocantes passados no açúcar e canela, acompanhados de doce de leite mineiro cremoso.",
    preco: "24.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Brownie de Nozes com Calda Quente de Fudge",
    descricao: "Bolo denso e úmido de puro cacau com pedaços crocantes de nozes pecan e bola de sorvete de creme.",
    preco: "25.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mousse de Maracujá com Sementes Crocantes",
    descricao: "Equilíbrio perfeito entre o doce e a acidez natural da fruta, finalizada com calda de maracujá fresca.",
    preco: "19.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mousse de Chocolate Meio Amargo 54%",
    descricao: "Textura leve e aerada preparada com chocolate nobre e raspas finas de cacau.",
    preco: "21.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Torta Holandesa com Biscoito Calipso",
    descricao: "Creme aveludado de baunilha sobre base crocante, cercada por biscoitos amanteigados e cobertura de ganache.",
    preco: "23.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Banoffee Pie com Doce de Leite e Chantilly",
    descricao: "Torta inglesa com fatias de banana fresca, camada espessa de doce de leite e chantilly polvilhado de cacau.",
    preco: "24.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cocada de Forno Cremosa Quente",
    descricao: "Coco ralado fresco assado com leite condensado até dourar, servida quente com sorvete de tapioca.",
    preco: "22.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Profiteroles Recheados com Ganache de Avelã",
    descricao: "Carolinas francesas assadas recheadas de sorvete de baunilha e regadas com calda quente de avelã.",
    preco: "26.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Torta de Limão Siciliano com Merengue Tostado",
    descricao: "Massa sablée crocante com creme de limão azedinho na medida e merengue suíço maçaricado.",
    preco: "22.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Torta de Maçã Quente com Canela e Sorvete",
    descricao: "Clássica apple pie com fatias de maçã caramelizadas com canela em massa folhada crocante.",
    preco: "25.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Gelato Artesanal Italiano (2 Bolas)",
    descricao: "Sabores à escolha: Pistache Siciliano, Doce de Leite, Morango Silvestre ou Chocolate Amargo.",
    preco: "21.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mil Folhas de Baunilha e Açúcar de Confeiteiro",
    descricao: "Folhagem crocante e delicada intercalada com creme pâtissière aromatizado com sementes de baunilha.",
    preco: "27.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Pavê Tradicional de Chocolate e Biscoito Champanhe",
    descricao: "Camadas suaves de creme branco, biscoito umedecido em leite achocolatado e cobertura cremosa de chocolate.",
    preco: "19.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Quindim Tradicional com Côco Fresco",
    descricao: "Doce conventual de gemas frescas, açúcar e coco ralado, brilhante e com base crocante de coco.",
    preco: "16.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Fondue Individual de Chocolate com Morangos",
    descricao: "Panelinha quente com blend cremoso de chocolates nobres, acompanhada de morangos frescos e banana em rodelas.",
    preco: "36.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Goiabada Cascão com Queijo Minas Meia Cura",
    descricao: "O legítimo Romeu e Julieta com fatias generosas de queijo curado na serra e goiabada cremosa da fazenda.",
    preco: "17.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mousse de Café Expresso com Grãos Tostados",
    descricao: "Sobremesa aerada para apreciadores de café, com notas marcantes de grãos moídos e raspas de cacau.",
    preco: "20.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Pera ao Vinho Tinto e Especiarias",
    descricao: "Pera Williams cozida suavemente em vinho tinto encorpado, canela em pau, anis estrelado e sorvete de nozes.",
    preco: "26.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cartola Pernambucana Tradicional",
    descricao: "Bananas fritas na manteiga com queijo manteiga derretido tostado, açúcar refinado e canela em pó.",
    preco: "22.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Panqueca de Doce de Leite com Canela",
    descricao: "Massa fininha e leve recheada com doce de leite morno argentino e polvilhada com açúcar.",
    preco: "21.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Affogato al Caffè com Amêndoas",
    descricao: "Uma dose de espresso italiano quente tirado na hora diretamente sobre uma bola de sorvete de fior di latte.",
    preco: "18.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Torta Trufada de Chocolate Branco e Pistache",
    descricao: "Creme aveludado de chocolate branco com pasta pura de pistache sobre crosta de biscoitos de amêndoas.",
    preco: "28.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Salada de Frutas Tropicais com Raspas de Hortelã",
    descricao: "Seleção fresca do dia: morangos, melão, abacaxi pérola, manga e uvas com suco natural de laranja.",
    preco: "15.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cannoli Siciliano com Ricota Doce e Pistache",
    descricao: "Canudo frito crocante aromatizado com vinho marsala, recheado com creme de ricota de ovelha e gotas de chocolate.",
    preco: "23.00",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Bolo Gelado de Coco Embrulhado no Alumínio",
    descricao: "Bolo de massa fofa bem molhado em calda de leite condensado e leite de coco, polvilhado com coco fresco.",
    preco: "16.50",
    categoria: "SOBREMESAS",
    imagem: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=600&q=80",
  },

  // ================= BEBIDAS (30 ITENS) =================
  {
    nome: "Suco Natural de Laranja Pera (500ml)",
    descricao: "Laranjas espremidas na hora sem adição de açúcar ou água. Puro frescor e vitamina C.",
    preco: "12.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Limonada Suíça com Leite Condensado (500ml)",
    descricao: "Limões tahiti batidos com gelo e leite condensado até criar espuma cremosa e refrescante.",
    preco: "15.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Soda Italiana de Maçã Verde com Gelo",
    descricao: "Xarope francês Monin de maçã verde com água gaseificada gelada e fatias de limão siciliano.",
    preco: "16.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Soda Italiana de Frutas Vermelhas",
    descricao: "Bebida frisante e doce elaborada com xarope artesanal de amora, framboesa e morango.",
    preco: "16.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Água Mineral com Gás Prata (300ml)",
    descricao: "Água mineral puríssima de fonte com gás natural e frescor equilibrado.",
    preco: "7.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Água Mineral sem Gás Prata (300ml)",
    descricao: "Água mineral cristalina, servida com ou sem gelo e rodela de limão a pedido.",
    preco: "6.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Refrigerante Coca-Cola Tradicional (Lata 350ml)",
    descricao: "Sabor original, servido trincando de gelado com fatia de limão.",
    preco: "8.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Refrigerante Coca-Cola Zero (Lata 350ml)",
    descricao: "Zero açúcar com máximo sabor, servido gelado.",
    preco: "8.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Refrigerante Guaraná Antarctica (Lata 350ml)",
    descricao: "O sabor genuíno da fruta brasileira na lata tradicional bem gelada.",
    preco: "8.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Água Tônica Schweppes (Lata 350ml)",
    descricao: "Gaseificação fina com amargor suave de quinino natural.",
    preco: "8.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Suco Detox Verde Especial (500ml)",
    descricao: "Bebida funcional energizante com couve manteiga, abacaxi, maçã verde, gengibre fresco e hortelã.",
    preco: "16.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Suco Natural de Abacaxi com Hortelã",
    descricao: "Polpa fresca de abacaxi batida com folhas de hortelã aromática e gelo filtrado.",
    preco: "13.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Suco Natural de Maracujá da Fruta",
    descricao: "Polpa 100% natural de maracujá fresco batida com água mineral e adoçada conforme preferência.",
    preco: "14.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Suco Natural de Melancia com Gengibre",
    descricao: "Melancia doce e refrescante com um leve toque picante de gengibre ralado.",
    preco: "13.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Chá Gelado de Pêssego Artesanal (400ml)",
    descricao: "Infusão de folhas de chá preto com néctar suave de pêssego e gelo triturado.",
    preco: "12.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Chá Gelado de Limão Siciliano com Manjericão",
    descricao: "Chá verde infusionado a frio com fatias de limão e folhas de manjericão fresco da horta.",
    preco: "13.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Água de Coco Natural da Bahia (350ml)",
    descricao: "Retirada diretamente do coco verde selecionado, servida natural ou gelada.",
    preco: "10.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cerveja Heineken Long Neck (330ml)",
    descricao: "Lager premium puro malte, cor dourada marcante e amargor equilibrado.",
    preco: "14.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1608270114034-72534571e7a5?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cerveja Stella Artois Long Neck (330ml)",
    descricao: "Cerveja belga com mais de 600 anos de tradição, lúpulos selecionados e aroma floral.",
    preco: "13.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1608270114034-72534571e7a5?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cerveja Artesanal IPA Colorado Indica (600ml)",
    descricao: "India Pale Ale brasileira lupulada, encorpada e com toque sutil de rapadura.",
    preco: "26.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1608270114034-72534571e7a5?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cerveja Artesanal Witbier com Cascas de Laranja (600ml)",
    descricao: "Cerveja de trigo leve e refrescante com sementes de coentro e raspas de laranja da terra.",
    preco: "25.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1608270114034-72534571e7a5?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Caipirinha Clássica de Cachaça Envelhecida",
    descricao: "Limão tahiti fresco macerado com açúcar orgânico e cachaça mineira descansada em carvalho.",
    preco: "24.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Caipivodka de Frutas Vermelhas com Hortelã",
    descricao: "Vodka premium batida com morangos, amoras frescas e folhas aromáticas de hortelã.",
    preco: "29.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Aperol Spritz Veneziano",
    descricao: "Aperol original, espumante Prosecco italiano bem gelado, água gaseificada e fatia de laranja bahia.",
    preco: "34.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Gin Tônica Clássico com Especiarias",
    descricao: "Gin botânico artesanal, tônica premium, zimbro tostado e ramo de alecrim fresco.",
    preco: "33.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Mojito Cubano Tradicional",
    descricao: "Rum branco caribenho, hortelã fresca macerada, suco de limão, açúcar e club soda com muito gelo.",
    preco: "27.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Café Expresso Especial Grão Arábica",
    descricao: "Extraído sob pressão ideal com crema aveludada, notas de caramelo e chocolate.",
    preco: "7.50",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cappuccino Italiano com Canela e Cacau",
    descricao: "Espresso curto combinado com leite vaporizado sedoso e polvilhado de cacau 100% e canela.",
    preco: "13.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Chocolate Quente Cremoso Europeu",
    descricao: "Feito com chocolate meio amargo derretido no leite e finalizado com chantilly de baunilha.",
    preco: "16.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Energético Red Bull Energy Drink (Lata 250ml)",
    descricao: "Revitaliza corpo e mente com fórmula com cafeína e taurina gelada.",
    preco: "16.00",
    categoria: "BEBIDAS",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
  },

  // ================= CARTA DE VINHOS (30 ITENS) =================
  {
    nome: "Vinho Tinto Catena Zapata Malbec (Mendoza - ARG)",
    descricao: "Vinho ícone com aromas complexos de frutas pretas maduras, baunilha, notas de cedro e taninos sedosos.",
    preco: "185.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Vinho Tinto DV Catena Cabernet-Malbec (ARG)",
    descricao: "Blend harmonioso envelhecido em barricas francesas com notas de ameixa, cacau e especiarias doces.",
    preco: "165.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Vinho Tinto Casillero del Diablo Cabernet Sauvignon (CHI)",
    descricao: "Vinho chileno consagrado com coloração rubi intensa, corpo médio e notas de groselha e carvalho tostado.",
    preco: "85.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Carménère Montes Reserva (Colchagua - CHI)",
    descricao: "Taninos redondos com presença de pimentão doce assado, amoras e chocolate amargo.",
    preco: "98.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Miolo Lote 43 Merlot-Cabernet (Vale dos Vinhedos - BRA)",
    descricao: "Homenagem ao patriarca italiano, um dos tintos mais premiados do Brasil com excelente estrutura.",
    preco: "175.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Vinho Tinto Guaspari Vista da Serra Syrah (Espírito Santo do Pinhal - BRA)",
    descricao: "Vinho de altitude com dupla poda brasileiro com aroma floral exuberante e pimenta preta elegante.",
    preco: "220.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Quinta do Crasto Douro DOC (POR)",
    descricao: "Blend de castas autóctones do Douro português com fruta pura, frescor mineral e taninos aveludados.",
    preco: "140.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Cartuxa Évora DOC (Alentejo - POR)",
    descricao: "Produzido pela Fundação Eugénio de Almeida, estruturado, elegante e persistente no final de boca.",
    preco: "260.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Vinho Tinto Chianti Classico DOCG Ruffino (Toscana - ITA)",
    descricao: "Sangiovese vibrante com notas de cereja madura, violetas, boa acidez e perfeita vocação gastronômica.",
    preco: "155.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Brunello di Montalcino DOCG Banfi (Toscana - ITA)",
    descricao: "Envelhecido por anos em tonéis de carvalho com grande complexidade aromática de couro, fumo e frutas secas.",
    preco: "490.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Barolo DOCG Batasiolo (Piemonte - ITA)",
    descricao: "O rei dos vinhos italianos elaborado com uva Nebbiolo, notas de rosas secas, alcatrão e taninos firmes.",
    preco: "420.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Primitivo di Manduria San Marzano (Puglia - ITA)",
    descricao: "Encorpado e aveludado, com notas quentes de geleia de amora, cerejas maceradas e tabaco.",
    preco: "135.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Bordeaux Supérieur Château Pey La Tour (FRA)",
    descricao: "Predomínio de uva Merlot com toque de Cabernet, frutas vermelhas frescas e taninos redondos.",
    preco: "148.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Châteauneuf-du-Pape E. Guigal (Rhône - FRA)",
    descricao: "Aromas ricos de ervas de Provença, frutas negras compotadas e especiarias orientais refinadas.",
    preco: "380.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Marqués de Riscal Reserva Rioja (ESP)",
    descricao: "Uva Tempranillo com passagem longa por carvalho americano, notas balsâmicas, baunilha e frutas maduras.",
    preco: "195.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Tinto Ribera del Duero Pesquera Crianza (ESP)",
    descricao: "Tinto espanhol poderoso e elegante com aromas tostados de carvalho francês e frutas negras intensas.",
    preco: "245.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Branco Catena Chardonnay (Mendoza - ARG)",
    descricao: "Fermentado em barricas, amanteigado com aromas de maçã assada, abacaxi maduro e notas minerais.",
    preco: "145.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Vinho Branco Sauvignon Blanc Leyda Reserva (CHI)",
    descricao: "Influência marítima do Pacífico, fresco com aromas herbáceos cítricos e maracujá verde.",
    preco: "95.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Branco Vinho Verde Casal Garcia (POR)",
    descricao: "Levemente frisante, fresco e cítrico, ideal para acompanhar frutos do mar e dias ensolarados.",
    preco: "68.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Branco Alvarinho Deu la Deu Monção e Melgaço (POR)",
    descricao: "Um dos brancos mais prestigiados de Portugal com notas de pêssego branco, floral e acidez viva e mineral.",
    preco: "135.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Branco Pinot Grigio delle Venezie Santa Cristina (ITA)",
    descricao: "Frutas de polpa branca delicadas, acidez equilibrada e frescor que limpa o paladar.",
    preco: "115.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Branco Chablis Domaine William Fèvre (Borgonha - FRA)",
    descricao: "Chardonnay francês puro sem madeira com mineralidade pura de pedra de sílex e acidez eletrizante.",
    preco: "320.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho Rosé Whispering Angel Côtes de Provence (FRA)",
    descricao: "O rosé mais famoso do mundo, cor casca de cebola pálida com notas sutis de morango fresco e flor de laranjeira.",
    preco: "270.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Vinho Rosé Casillero del Diablo Shiraz Rosé (CHI)",
    descricao: "Aromas atraentes de framboesas e amoras silvestres, paladar fresco e final frutado prolongado.",
    preco: "79.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Espumante Casa Valduga 130 Brut Tradicional (BRA)",
    descricao: "Método tradicional brasileiro envelhecido 36 meses sobre leveduras com perlage finíssima e aromas de brioche.",
    preco: "148.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Espumante Chandon Réserve Brut (Serra Gaúcha - BRA)",
    descricao: "Aroma fresco de frutas cítricas e flores brancas, com paladar cremoso e muito equilíbrio.",
    preco: "110.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Champagne Veuve Clicquot Ponsardin Brut (FRA)",
    descricao: "O champagne da icônica etiqueta amarela com notas tostadas, maçã madura e elegância insuperável.",
    preco: "560.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
    destaque: 1,
  },
  {
    nome: "Champagne Moët & Chandon Impérial Brut (FRA)",
    descricao: "Equilíbrio refinado de Pinot Noir, Meunier e Chardonnay com borbulhas abundantes e festivas.",
    preco: "510.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho do Porto Ferreira Tawny (Douro - POR)",
    descricao: "Vinho fortificado doce com envelhecimento em cascos de carvalho, notas de passas, figos secos e nozes.",
    preco: "125.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Vinho de Sobremesa Sauternes Château Guiraud (FRA)",
    descricao: "Vinho nobre de colheita tardia afetado por podridão nobre com aromas suntuosos de mel, damascos e especiarias.",
    preco: "290.00",
    categoria: "CARTA DE VINHOS",
    imagem: "https://images.unsplash.com/photo-1558001373-4b93f47d4e5f?auto=format&fit=crop&w=600&q=80",
  },
];

async function main() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error("DATABASE_URL is not set");
    process.exit(1);
  }

  const pool = mysql.createPool(databaseUrl);
  const db = drizzle(pool);

  console.log(`Starting seed with ${SEED_PRODUTOS.length} products...`);

  // Count by category
  const categoriesCount: Record<string, number> = {};
  for (const item of SEED_PRODUTOS) {
    categoriesCount[item.categoria] = (categoriesCount[item.categoria] || 0) + 1;
  }
  console.log("Distribution by category:", categoriesCount);

  // Clear existing products to ensure clean seed
  console.log("Truncating / clearing existing produtos...");
  await pool.execute("TRUNCATE TABLE produtos;");

  // Insert in batches
  const batchSize = 25;
  for (let i = 0; i < SEED_PRODUTOS.length; i += batchSize) {
    const chunk = SEED_PRODUTOS.slice(i, i + batchSize).map((p) => ({
      nome: p.nome,
      descricao: p.descricao,
      preco: p.preco,
      categoria: p.categoria,
      imagem: p.imagem,
      destaque: p.destaque ?? 0,
      ativo: 1,
    }));
    await db.insert(produtos).values(chunk);
    console.log(`Inserted batch ${i + 1} to ${Math.min(i + batchSize, SEED_PRODUTOS.length)}`);
  }

  const [totalCountResult] = await db.select({ value: count() }).from(produtos);
  console.log(`\nSeed completed successfully! Total products in database: ${totalCountResult?.value}`);
  await pool.end();
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
